name: CLDF-validation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest-cldf
    - name: Test with pytest
      run: |
        pytest --cldf-metadata=mega-merge/output/logicalMM/cldf/StructureDataset-MM-logical-metadata.json test.py
        pytest --cldf-metadata=mega-merge/output/statisticalMM/cldf/StructureDataset-MM-statistical-metadata.json test.py
        pytest --cldf-metadata=grambank-modified/output/logicalGBM/cldf/StructureDataset-GBM-logical-metadata.json test.py
        pytest --cldf-metadata=grambank-modified/output/statisticalGBM/cldf/StructureDataset-GBM-statistical-metadata.json test.py
